export const CART_ADD_ITEM = 'CART_ADD_ITEM'
export const CART_UPDATE_ITEM = 'CART_UPDATE_ITEM'
export const CART_UPDATE_TOTALPRICE = 'CART_UPDATE_TOTALPRICE'

export const CHANGE_FILTER_SECTION = "CHANGE_FILTER_SECTION"
export const CHANGE_FILTER_GENRES = "CHANGE_FILTER_GENRES"
export const CHANGE_FILTER_CATEGORY = "CHANGE_FILTER_CATEGORY"
